### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by evhumphrey** [th0r0nd0r/Barebnb#6]
Comment Updated, misinformation was here. Heroku does need to be set up though!

**Comment by th0r0nd0r** [comment]
Hey @evhumphrey ! I'm pretty happy with my user auth, so I'm ready for a code review.  The functionality is all there, but there are a couple sections that I would appreciate a careful look at:

-I want the background image on my landing page to exactly fill up the screen, with content scrollable on top.  As it is now, there is some white space at the bottom.
-for my demo login, I seeded the database with some demo users, and then put an array of the demo users in my login_form state.  I considered putting them in the greater session slice of state and passing them as props through the login_form_container, but I didn't know how to use an ajax request to pull _just __ the demo users from the database.  Let me know if this is an ok way to do it, or if I should change some things.

thanks!

**Comment by th0r0nd0r** [comment]
Also, is there an easy way to better resize the user's avatar images in the nav bar?  If they're not square they get kind of squished right now.
